/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: elenstesh (https://sketchfab.com/elenstesh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robot-eva-855370cceb594490b8375698098d6ad5
Title: robot Eva
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Robot(props) {
  const { nodes, materials } = useGLTF('/robot_eva.glb')
  return (
    <group {...props} dispose={null}>

        {/* Head part  rotation X, Y=right/-ve left, Z=up/-ve down*/}
        <group rotation={[0,0,0]}>
            {/* Hoodie */}
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_6.geometry}
                material={materials.material}
                position={[1.628, 3.8, -0.139]}
                scale={[1.6, 1.183, 1.183]}
            />

            {/* Black face */}
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_8.geometry}
                material={materials['.001']}
                position={[1.628, 3.8, -0.139]}
                scale={[1.6, 1.183, 1.183]}
            />

            {/* Eye left */}
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_14.geometry}
                material={materials['.004']}
                position={[1.628, 3.8, -0.139]}
                scale={[1.6, 1.183, 1.183]}
            />
            {/* Eye right */}
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_16.geometry}
                material={materials['.004']}
                position={[1.628, 3.8, -0.139]}
                scale={[1.6, 1.183, 1.183]}
            />
        </group>


        {/* Body */}
        <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.material}
        position={[-0.313, 0.232, -0.124]}
        scale={1.29}
      />
      {/* Hands */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.material}
        position={[-0.332, 1.101, -2.014]}
        scale={[0.554, 1.58, 0.126]}
      />

    {/* Neck ring */}
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials['.002']}
        position={[-0.313, 0.236, -0.124]}
        scale={1.29}
      /> */}

    </group>
  )
}

useGLTF.preload('/robot_eva.glb')
