import type { Metadata } from "next";

import "./globals.css";
import ThemeToggler from "@/components/BaseEffects/ThemeToggler";
import { ThemeProvider } from "@/providers/theme-provider";
import MainModal from "@/components/mainModal";

import SmoothScrollbar from '../components/BaseEffects/SmoothScrollbar';
import Navbar from "@/components/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en" className="relative" suppressHydrationWarning>
      <body className="Poppins"
      >

      {/* <SmoothScrollbar> */}

        <ThemeProvider
        attribute="class"
        defaultTheme="dark"
        themes={["light", "dark", "neon"]}
        >



          {/* <MainModal/> */}
          {children}

          <div className="absolute top-2 right-2">
            {/* <ThemeToggler/> */}
          </div>


          <footer></footer>


        </ThemeProvider>

        <Navbar/>

     {/* </SmoothScrollbar> */}

      </body>
    </html>

  );
}
